### ISSUE TITLE
OAUTH doc link is wrong

### ISSUE THREAD

**Issue by hgouveia** [Patreon/patreon-php#1]
the link in  "Visit the **OAuth Documentation Page** while logged in as a Patreon creator to register your client."  

As it said, is only for Patreon Creators, im a Patreon User but im not a creator, i just want to get API access to develop a section in a customer page, that wants to show Patreon only content , why is this only available for Creators?

**Comment by hgouveia** [comment]
closing, because i just realized that the access is related to an specific patreon campaign

**Comment by 21echoes** [comment]
Hey @hgouveia ! Thanks for writing in. To clarify -- the OAuth Documentation page is available to all Patreon creators, not just a specific patreon campaign. The site was down last night (PST) due to Amazon running unexpected & unwarned maintenance on our cluster, but the documentation should be accessible now if you are a creator.

We are currently limiting API key registration access to Patreon creators, but if you want to write in to david-at-patreon-dot-com with an explanation of how you'd like to use the API as a patron, we can reconsider that position.

Thanks again!
