### ISSUE TITLE
Failed to get this working

### ISSUE THREAD

**Issue by jantje** [Patreon/patreon-php#2]
Hi 
I'm new to oAuth and not fluent in php so it is probably obvious what I did wrong but I failed to get this to work.
What I did.
On my website I made a folder patreon. I created a file mypatreon.php with the content of the php in read.me file.
I copied the patreon.php and the Patreon folder in the patreon folder I already created.
I replaced the section 
`$client_id = "Client ID:";      // Replace with your data
$client_secret = "Client Secret:";  // Replace with your data
$creator_id = "Creator's Access Token:";     // Replace with your data`
I got client ID and Client Secret and Creator's Access Token from patreon.com

I enabled php error output and from the following code
`$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$tokens = $oauth_client->get_tokens($_GET['code'], "http://localhost:5000/oauth/redirect");
$access_token= $tokens['access_token'];
 echo "access_token = " ,$access_token,"<br>";
$api_client = new Patreon\API($access_token);
$user_response = $api_client->fetch_user();
 echo "user_response = " ,$user_response,"<br>";
$user = $user_response['data'];
 echo "user = " ,$user,"<br>";
`
I get
`access_token =
user_response =
user = `
What did I do wrong?

**Comment by 21echoes** [comment]
Hey there!

1. `$creator_id` should not be equal to Creator's Access Token. Creator ID is your user ID on patreon.com. It's not necessary given the issues you're running into now, but figured I should point this out.
2. when you registered your client on patreon.com, did you put in `http://localhost:5000/oauth/redirect` as one of your redirect URIs? This redirect URI must match one of the ones you registered.

If you want to send me your patreon profile URL I can help debug further, if point 2 right there doesn't solve the issue.

**Comment by jantje** [comment]
Still not working.
Still lots of things I do not get.
This is my patron URL: https://www.patreon.com/jantje?ty=h
My ID on patreon is that jantje or the email address or something else?
I tried both without success.
I have no clue what this redirect uri is all about. So I entered a url that links to my web site but there is no such file ( the url's I provided for "Privacy Policy URL" and "Terms of Service URL" do not exists as well)

```
$creator_id = "eclipse@baeyens.it";     // Replace with your data
$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$tokens = $oauth_client->get_tokens($_GET['code'], "https://patreon.baeyens.it/oauthredirect.php");
$access_token= $tokens['access_token'];
 echo "access_token = " ,$access_token,"<br>";
$api_client = new Patreon\API($access_token);
$user_response = $api_client->fetch_user();
 echo "user_response = " ,$user_response,"<br>";
$user = $user_response['data'];
 echo "user = " ,$user,"<br>";
```
and also with creator id jantje but I always get
>access_token =        
user_response =       
user =

**Comment by jantje** [comment]
ok I understand now why I do not get any info. No patrons have allowed me access to their data.
I think the example is pretty good but some more info on what it exactly does and why you should use it would be appreciated.

**Comment by 21echoes** [comment]
You should still be able to get your own data, including the list of your patrons, just fine! i think you're running into a separate issue -- can you please paste in the entirety of the code you're trying so I can help you debug?

**Comment by jantje** [comment]
Here is the code. I x'ed out part of the $client_id and $client_secret 


```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Thanks for using our plugin.</title>
<link href="MyStyle.css" rel="Stylesheet" type="text/css">
</head>
<body>

<p>Some stuff at the start</p>

<?php

require_once('patreon.php');

use Patreon\API;
use Patreon\OAuth;

$client_id = "411xxxxxxxxxxxxx";      // Replace with your data
$client_secret = "43e47778175xxxxxx";  // Replace with your data
$creator_id = "jantje";     // Replace with your data

$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$tokens = $oauth_client->get_tokens($_GET['code'], "https://patreon.baeyens.it/oauthredirect.php");
$access_token= $tokens['access_token'];
 echo "access_token = " ,$access_token,"<br>";
$api_client = new Patreon\API($access_token);
$user_response = $api_client->fetch_user();
 echo "user_response = " ,$user_response,"<br>";
$user = $user_response['data'];
 echo "user = " ,$user,"<br>";
$included = $user_response['included'];
$pledge = null;
$campaign = null;
if ($included != null) {
  foreach ($included as $obj) {
    if ($obj["type"] == "pledge" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $pledge = $obj;
      break;
    }
  }
  foreach ($included as $obj) {
    if ($obj["type"] == "campaign" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $campaign = $obj;
      break;
    }
  }
  echo "use " ,$user, "," ,$pledge, ", and" ,$campaign, "as desired","<br>";
}
?>
Some stuff at the end

</body>
</html>
```

**Comment by teknoaxe** [comment]
Hey,

I'm running into the same issue, where I'm not getting any sort of response from using this code.  I believe that I corrected one of the errors in the original poster's code, but there is also one other difference in my code.

In this case, the GET is replaced by request_var.  This is because the PHPBB3 that runs some of the community and blogging based features on my site disallows the use of GET as they consider this a security threat to users.

In any case, all I'm looking to do is get a list of my patreons so I can give them a little bit of real-estate and recognition on my website.


Thank you!
Matt

Code:
----------------------
<?php
  require_once "Patreon/patreon.php";

  use Patreon\API;
  use Patreon\OAuth;


  $client_id = "xxxxxxxx";      // Replace with your data
  $client_secret = "xxxxxxx";  // Replace with your data
  $creator_id = "teknoaxe";     // Replace with your data

  $oauth_client = new Patreon\OAuth($client_id, $client_secret);
  $tokens = $oauth_client->get_tokens(request_var("code",""), "http://www.teknoaxe.com/Sponsors.php");
  $access_token = $tokens['access_token'];

  $api_client = new Patreon\API($access_token);
  $user_response = $api_client->fetch_user();
  $user = $user_response['data'];
  $included = $user_response['included'];
  $pledge = null;
  $campaign = null;
  if ($included != null) {
    foreach ($included as $obj) {
      if ($obj["type"] == "pledge" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
        $pledge = $obj;
      
        break;
      }
    }
    foreach ($included as $obj) {
      if ($obj["type"] == "campaign" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
        $campaign = $obj;
        break;
      }
    }
  echo "user " ,$user, "," ,$pledge, ", and" ,$campaign, "as desired","<br>";
  }
  echo $user;
  //$patreons = fetch_campaign_and_patrons();
?>

**Comment by 21echoes** [comment]
Hey @jantje and @teknoaxe ! I copy / pasted your code and it works fine for me locally. I'd recommend you modify your code as follows on your end to help me help you debug it:

```php
...
$my_redirect_url = "http://localhost:5000/oauth/redirect"; // or whatever your redirect url is

$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$oauth_grant_code = $_GET["code"]; // or request_var("code", "ERROR: NO CODE");
 echo "oauth_grant_code = ",$oauth_grant_code,"<br/>";
$tokens = $oauth_client->get_tokens($oauth_grant_code, $my_redirect_url);
 echo "tokens = ",print_r($tokens),"<br/>";
$access_token= $tokens['access_token'];
 echo "access_token = " ,$access_token,"<br>";
$api_client = new Patreon\API($access_token);
$user_response = $api_client->fetch_user();
 echo "user_response = " ,print_r($user_response),"<br>";
$user = $user_response['data'];
 echo "user = " ,print_r($user),"<br>";
$included = $user_response['included'];
$pledge = null;
$campaign = null;
if ($included != null) {
  foreach ($included as $obj) {
    if ($obj["type"] == "pledge" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $pledge = $obj;
      break;
    }
  }
  foreach ($included as $obj) {
    if ($obj["type"] == "campaign" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $campaign = $obj;
      break;
    }
  }
  echo "use " ,print_r($user), "," ,print_r($pledge), ", and" ,print_r($campaign), "as desired","<br>";
}
...
```

that way you can make sure you are getting the OAuth Grant Code and using it correctly (debugging why you may not be receiving any tokens back from us)

**Comment by jantje** [comment]
I tried your code and this is the output
```
Some stuff at the start
oauth_grant_code =
tokens = Array ( [error_description] => Missing code parameter. [error] => invalid_request ) 1
access_token =
user_response = 1
user = 1
Some stuff at the end 
```

The whole code I used is (with cripled data and id)
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Thanks for using our plugin.</title>
<link href="MyStyle.css" rel="Stylesheet" type="text/css">
</head>
<body>

<p>Some stuff at the start</p>

<?php

require_once('patreon.php');

use Patreon\API;
use Patreon\OAuth;

$client_id = "411----------------------------------------a04c722a9f287d569c38c";      // Replace with your data
$client_secret = "43e4----------------------------------------2a5d9b4a112e70ed1d00";  // Replace with your data
$creator_id = "jantje";     // Replace with your data



$my_redirect_url = "http://localhost:5000/oauth/redirect"; // or whatever your redirect url is

$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$oauth_grant_code = $_GET["code"]; // or request_var("code", "ERROR: NO CODE");
 echo "oauth_grant_code = ",$oauth_grant_code,"<br/>";
$tokens = $oauth_client->get_tokens($oauth_grant_code, $my_redirect_url);
 echo "tokens = ",print_r($tokens),"<br/>";
$access_token= $tokens['access_token'];
 echo "access_token = " ,$access_token,"<br>";
$api_client = new Patreon\API($access_token);
$user_response = $api_client->fetch_user();
 echo "user_response = " ,print_r($user_response),"<br>";
$user = $user_response['data'];
 echo "user = " ,print_r($user),"<br>";
$included = $user_response['included'];
$pledge = null;
$campaign = null;
if ($included != null) {
  foreach ($included as $obj) {
    if ($obj["type"] == "pledge" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $pledge = $obj;
      break;
    }
  }
  foreach ($included as $obj) {
    if ($obj["type"] == "campaign" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $campaign = $obj;
      break;
    }
  }
  echo "use " ,print_r($user), "," ,print_r($pledge), ", and" ,print_r($campaign), "as desired","<br>";
}

?>
Some stuff at the end

</body>
</html>
```

**Comment by teknoaxe** [comment]
Hi 21echoes,

here's the output that I got with your modified code.  It's pretty much the same as jantje.  I replaced my ID username with the number that Evan Keith (is that you?) provided me over email.

------------------------
oauth_grant_code = 
tokens = Array ( [error] => invalid_grant ) 1
access_token = 
user_response = 1
user = 1
-------------------------

Evan also suggested that I move the patreon code over to the redirect address, which I'm slightly confused about.  Is that an actual place on my server?

Thanks,
Matt

**Comment by 21echoes** [comment]
`oauth_grant_code` being blank is the problem for each of you. You need to have received a grant code as a query parameter as a result of sending the user to our OAuth approval page. Please read through the documentation at [https://www.patreon.com/platform/documentation/oauth](https://www.patreon.com/platform/documentation/oauth) (specifically, it seems as though you are each trying to start at step 3 without going thru steps 1 and 2 first)

**Comment by teknoaxe** [comment]
Hi David,

Thanks for your help! I followed what you said and I was able to get data
from the GET address, and all of the information about my patreon account,
including my campaign and patreons.

I have two follow-up questions:

1. I'm assuming that I want to somehow hide the client ID when requesting
API info from Patreon, so I just want to confirm I want to keep that info
secure.

2.  When performing the GET function on your site, patreon asks "Matthew
Huffaker wants permission to access your..."

So the reason that I wanted access to the API is so that I could have my
website set up donation spots and some space on my webpage for an up to
date list of every one of my patrons.

With this type of authorization, it looks as though the process can't be as
automated as that, where the code automatically populates the page every
time a user clicks on the page, but instead it's something that I would
perform to keep the page up to date. Is this correct?

Again, thank you for your help!
Matt

**Comment by 21echoes** [comment]
Hey Matt! Glad to hear it.

1. Secrecy
The client ID is public, it's only the client secret and any resulting tokens that you should keep secret.

2. Usage
I think I'm reading your use case as not really needing your patrons to verify they are patrons, but rather to keep your own data up to date for display purposes. If that's the case, I'd recommend just using your own authorization token and never sending any users of your website through this flow. You can get your refresh token [here as "Creator's Refesh Token"](https://www.patreon.com/platform/documentation/clients). Something like this should work:

```php
...
$oauth_client = new Patreon\OAuth($client_id, $client_secret);
$my_refresh_token = "XXXX"; // from https://www.patreon.com/platform/documentation/clients
$tokens = $oauth_client->refresh_token($my_refresh_token, "");
$new_refresh_token = $tokens['refresh_token']; // save this off for future usage as $my_refresh_token, perhaps in your database
$access_token = $tokens['access_token'];

$api_client = new Patreon\API($access_token);
...
```

**Comment by jantje** [comment]
Cool. It seems like you found the root cause. I don't have time now but I'll look into this the early next week.

**Comment by teknoaxe** [comment]
Hey David,

Thanks again for your help.  I'm now using the client access token that is
on my account and it seems to be working fine.  Sorry to pick your brain
some more, but right now I'm looking at a few other things that I need to
clarify to make things pretty on my end.

For now, I'm using the "fetch_campaign_and_patrons()" function of the API
to get all data.  While it gets all the data, the structure looks like a
mess, with my patreons starting at somewhere around '["included"][24]'.
Looking through the API.php set of functions, I'm going to assume that
"fetch_page_of_pledges" is better for returning a set of my patrons and
their data, but I need to know a little more about the arguments passed to
that function.  $campaign_$id seems straight forward--that's the ID
associated with my patreon account.  With $page_size, is this the number of
patrons that I fetch at one time?  Is there a way I can set this value to
all of them?  I'm unsure what to do with the $cursor argument as well.

Again thanks for the help!  You've helped tremendously.

Matt

**Comment by jantje** [comment]
I fail to understand.
Do I need to make a button that will redirect to my page and then it will work?

**Comment by teknoaxe** [comment]
Hi David!

I just wanted to thank you for your help again.  I was able to work out the data structure of the function that I was using to retrieve my patron info, and this page is the result: http://teknoaxe.com/Sponsors.php.  It's just a spot on my site for the patreons, but it's what I promised them.

Jantje:

I think the requirement for the button is dependent on what you want to do.  If you're looking to just get info about your patrons, then all you need is to put the access token that's displayed on your client_id and client secret page instead of the function that gets a new token.  

For more in depth services, you have to construct a GET http: address to patreon.com, with your client_id and some other things:

eg: https://www.patreon.com/oauth2/authorize?response_type=code&client_id=[yourclientid]

patreon presents you with an authorization screen.  Once you hit "yes", patreon redirects to your redirect address with code as one of the arguments (hence the need for _GET in the php code, or in my case request_var.  I should have known this).

for me, the redirect would have looked like this (and I tried it, it works): 
http://www.teknoaxe.com/Sponsors.php?code=[new token Patreon gives you]

**Comment by 21echoes** [comment]
@jantje what @teknoaxe said :D -- if you are just using this API to fetch data, then you can [follow the instructions i laid out here](https://github.com/Patreon/patreon-php/issues/2#issuecomment-225409318). If you are using this as an authentication flow, so that your patrons can prove to your site that they are indeed patrons, then you'll probably need to re-read [the instructions](https://www.patreon.com/platform/documentation/oauth), especially steps 1 and 2.

@teknoaxe glad it's all working for you now! and thanks for helping out.

**Comment by jantje** [comment]
I'm still not getting it but it is working when using this API to fetch data approach.
I'm closing this issue.
Thanks for the support.

**Comment by Locojoe1994** [comment]
IM STUCK ON ALL MY STEPS I GOT PATREON PAID FOR A WHOLE YEAR N I STILL HAVNT GOT TO STEP ONE I DONT WHAT I JAVE TO DO FIRST N AND. ALL THE OTHER STEPS THAT FOLLOWS I DONT NO HOW TO LINK MY PATREON TO GITHUB N DONT NO HOW TO HET MY TOKEN EITHER IM GOING CRAZY I DONT HAVE ANYONE WHO COULD DO THIS FOR ME I NEED A STEP BY STEP GUIDE IM NEW TO THIS N DONT NO WHAT TO DO THEY DAY GO YO PATREON N ON THE LEFT SIDE YOU COULD LINK YOUR PATREON N GITHUB BUT I STILL DONT NO HOW IT EORKS COULD SOME ONE SEND ME A STEP BY STEP GUIDE I PAY FOR A WHOLE YEAR ON PATREON N I DONT WANT TO LISE MY MONEY IF THERE IS NOT A GUIDE STEP BY STEP FOR BIGGNERS FOR FIRST TIME USERS MY EMAIL IS carmencaquias047@gmail.com U COULD REACH ME THERE PLEASE I NEED HELP ALL I NEED IS A BIGGNERS STEP BY STEP GUIDE TO DO THIS I BOUGHT THE NEW ROG ALLY N I TRAVEL A LOT IT WOULD B NICE TO HAVE HAMES ON MY ROG ALLY INSTRAD OF CARRY ALL MY CONSOLE WITH ME 




THANK U VERY MUCH N WOULD LIKE TO. HERE FROM U SOON
