### ISSUE TITLE
About API capabilities

### ISSUE THREAD

**Issue by alromh87** [Patreon/patreon-php#29]
I would like to show latest pledges, along with latest pledge time, so I would like to know how can I get more information about API supported params, like for sorting, adding fields, etc.

If not implemented in this API I can do it just need to know what to send.

Thanks

**Comment by spencerhandley** [comment]
Hey @alromh87 !

Thank you so much for reaching out in regards to the Patreon API. I'm happy to help out with this.

By default, you should see the following information in your responses:
'amount_cents',
'created_at',
'declined_since',
'patron_pays_fees',
'pledge_cap_cents',
You have the ability to request some additional information using the JSONAPI spare fieldsets. Currently, the following parameters are available:

'amount_cents',
'total_historical_amount_cents',
'declined_since',
'created_at',
'pledge_cap_cents',
'is_paused',
'has_shipping_address',

As an example, if you need the fields `amount_cents`, `created_at` and `declined_since`, you'll use `fields[pledge]=amount_cents,created_at,declined_since`​.

The above parameters are subject to change, if you run into any issues please let us know.

For additional information on the Patreon API head over to our documentation site.

**Comment by alromh87** [comment]
Thanks a lot for your answer!!

So I can get the historical amount and since when it was created.

How about options for sorting?

**Comment by NPC** [comment]
@spencerhandley Can you please explain more, how do I specify these fields? I assume that I need to see is_paused flag to know if a pledge is active or not, do I need to hardcoded it to $url in fetch_page_of_pledges? Or is there a way to pass it to the method call?

**Comment by spencerhandley** [comment]
@NPC Yes, you'll want to put that into your query params. How you put it there is up to you. Hardcoding works fine.

**Comment by spencerhandley** [comment]
@alromh87 Sorry about the incredibly long delay here, somehow I missed your response. The API currently does unofficially support sorting, but we can't guarantee is reliability at the moment. To use it, you would pass a param like `&sort=updated` where `updated` is the field you want to sort by. It defaults to ascending order.

**Comment by NPC** [comment]
@spencerhandley Thanks for the reply, for the record (if someone else searches for this answer), square brackets should be encoded in this way:

`$url = "campaigns/{$id}/pledges?page%5Bcount%5D={$count}&fields%5Bpledge%5D=amount_cents,...`

Also, if you specify any additional field, you should specify all the needed fields, not just the optional ones, since API seems to treat this list as an override to its defaults.

PS Perhaps passing additional request parameters into method calls is a good candidate for expanding patreon-php lib. It pains me to hardcode stuff in a 3rd party library :)
