### ISSUE TITLE
Can't make it work...

### ISSUE THREAD

**Issue by cperonneaud** [Patreon/patreon-php#48]
Hi,

I'm trying to have my members login to Patreon and return to my website to get their email and the current pledge they have for my campaign. The idea here is to give my patrons more vote when I create polls so I'm creating a custom poll PHP page.

I've copied/paste your code in my script and it's working up until I try to get the current user, when I use the method fetch_user, I get the error : You do not have permission to view this OAuth.

Here is the URL I use to send my patrons to login : https://www.patreon.com/oauth2/authorize?response_type=code&client_id=<my client id>&redirect_uri=<my redirect url>

I've created a test account and pledged to my campaign to test. I can login on Patreon and get redirected on my website with the code parameter as explained in the snippet here.

Then I use the following code as shown here :

```
require_once('vendor/patreon/patreon/src/patreon.php');

use Patreon\API;
use Patreon\OAuth;
$oauth_client = new OAuth(<my client id>, <my client secret>);

/*
 * Make sure that you're using this snippet as Step 2 of the OAuth flow: https://www.patreon.com/platform/documentation/oauth
 * so that you have the 'code' query parameter.
 */
$tokens = $oauth_client->get_tokens($_GET['code'], BASE_URL);

$access_token = $tokens['access_token'];
$refresh_token = $tokens['refresh_token'];

$api_client = new API($access_token);
$patron_response = $api_client->fetch_user();
```

I debugged the tokens and they are correctly filled.
The problem when I use the fetch_user and it returns me the error.

I just need the user email and his pledge to my campaign (if he has any). How do I do that ?

Thanks in advance

**Comment by daedolon18** [comment]
Ok to answer my own question and after hours of trials and errors. This API seems to be either outdated or for v1.
Since I need the pledge amount, I need v2 it seems.

So to solve my problem, I had to update the url in the API.php file (just add the v2) :
`$api_endpoint = "https://api.patreon.com/oauth2/v2/" . $suffix;`

There was also an issue with the include in patreon.php :
`require_once(__DIR__ . '/../../../autoload.php');
require_once("Patreon/API.php");
require_once("Patreon/OAuth.php");`

Then for the code itself, here it is :
`<?php
/*
 * Use the following,
 * or if you installed via Composer, it should already be required via autoloader
 */
 
require_once('vendor/patreon/patreon/src/patreon.php');

use Patreon\API;
use Patreon\OAuth;
$oauth_client = new OAuth(CLIENT_ID, CLIENT_SECRET);

/*
 * Make sure that you're using this snippet as Step 2 of the OAuth flow: https://www.patreon.com/platform/documentation/oauth
 * so that you have the 'code' query parameter.
 */
$tokens = $oauth_client->get_tokens($_GET['code'], BASE_URL);

$access_token = $tokens['access_token'];
$refresh_token = $tokens['refresh_token'];

$api_client = new API($access_token);
$patron_response = $api_client->fetch_user();
/*
 * The $patron_response is now a [art4/json-api-client/Document](https://github.com/Art4/json-api-client/blob/master/docs/objects-document.md)
 * You can access its primary data via ->get('data')
 */
$patron = $patron_response->get('data');
$_SESSION['patron_email'] = $patron->attribute('email');
$_SESSION['patron_pledge'] = 0;
/*
 * Given a resource in the document, you can access its relationships with ->relationship->($relationship_name)
 * or check for a relationship's existence with ->has('relationships.relationship_name')
 */
if ($patron->has('relationships.memberships')) {
    /*
     * To look up the full resource that the relationship is referencing,
     * we have extended [art4/json-api-client/ResourceIdentifier](https://github.com/Art4/json-api-client/blob/master/docs/objects-resource-identifier.md)
     * with the `->resolve` method.
     * You pass in the original response document, and you get back a full resource,
     * with attributes, relationships, etc.
     */
    $pledge = $patron->relationship('memberships')->get(0)->resolve($patron_response);
	$_SESSION['patron_pledge'] = $pledge->attribute('currently_entitled_amount_cents') / 100;
}`

With this, I can store the email and the pledge (given in cents so I divide by 100 to have a full amount since I don't use cents on my campaign and don't need them for my custom vote feature).

Hope that'll help someone.

**Comment by emosesPatreon** [comment]
Hi @daedolon18, I'm glad you got a solution working for your problem, but I'd like to investigate and make sure there aren't any bugs on our end.  Can you please post your client ID (not secret!) here, or email it to platform@patreon.com so we can take a look at what's going on?

BTW, if you'd like to write code blocks, use three backticks (`) on a line by themselves, and then code in between, like this

````
```
some code
```
````

**Comment by daedolon18** [comment]
Hi,

Here is my client id : LLCZLF0fWcoEvQvdQEdaQ5qs0g5LmhJ9FHROLZ6uAgyJWvvBRB2e5D03Nzd5aaGl

Here is the url I use for my new poll feature if it's needed too : http://polls.gaweb-studio.com/id/1
(Warning: it's for an adult game)

It seems to work fine right now, my patrons started voting since yesterday and I didn't get any bug report while getting the proper vote results stored.

By the way, I forgot to mention another problem in your code :
You use the $patron to get the patron info but then use the $user variable when checking the relationship. It should be $patron instead of $user, right ? This is quite confusing for beginners like me at first since I thought maybe I needed to make another call to get the user data.

Hope that helps!

**Comment by B-iggy** [comment]
Hey @daedolon18 

I'm at 5 hours straight trying to get it work.
The documentation etc. didn't help.

Since you say it "works" my biggest hope are you at the moment.

So no matter what I try, I always get this message

`Fatal error: Uncaught Art4\JsonApiClient\Exception\AccessException: "data" doesn't exist in Document. in /var/www/html/empyrion-homeworld/vendor/art4/json-api-client/src/Document.php:74 Stack trace: #0 `

I already updated the latest Art4 github package on my server.
Also tried with your API v2 approach or without. Same result.

My little background:

I have a steam web API running my own little backend.
But Patreon as the **big** issue that we at the end don't know the connection between steam and patron.
So my goal that once the player logged in with Steam web api, that he logs in with Patreon.
That way I can match the Patron to our Steam player and give pledges ingame dependend on that.


Any help is greatly appreciated!

**Comment by Art4** [comment]
@B-iggy Can you please post some example code? Your error message show that you are using something like `$user->get('data')`, but there is no `data` attribute in this object. You can debug this by showing all possible attributes with something like `var_dump($user->getKeys());`.

**Comment by foohonpie** [comment]
Hi @B-iggy, I just hit this as well.  My issue was that I initially misunderstood the documentation and was trying to do $patron_response->get('data') on an initial page instead of the post-auth redirect page (the one that returns `code`).

After I split the flow properly, my redirect page was returning $patron_response->get('data') just fine.

I hope that helps.
