### ISSUE TITLE
This libarary should be marked as BETA - it's buggy

### ISSUE THREAD

**Issue by jaypan** [Patreon/patreon-php#64]
This library should be marked as a beta. The version that comes through Composer does NOT work properly. Use at your own risk. See more here: https://www.patreondevelopers.com/t/does-anyone-from-patreon-even-look-at-this-forum/1963/3

**Comment by codebard** [comment]
The changes which were made in this repo were not carried to packagist. Therefore the package in there is outdated.

You can use this updated lib (this one in github) which uses api v2 and you should be fine. People have been using it since some time now.

https://github.com/Patreon/patreon-php/issues/55#issuecomment-475226672

**Comment by jaypan** [comment]
I have no need anymore, as I ended up writing my own integration before I realized that the official version supported by Composer is entirely outdated.

The Patreon team is doing a pretty horrible job at providing integration with their product. I wouldn't even give it a passing grade.

**Comment by soatok** [comment]
@jaypan I have a maintained and actively developed fork that may work better for you and others' needs: https://github.com/soatok/patreon-php
