### ISSUE TITLE
Patron emails not verified?

### ISSUE THREAD

**Issue by LiamDawe** [Patreon/patreon-php#65]
Going with V2, it says we need to check their email is verified. From the user_details_and_patronage.php example:

> // This email may or may not be verified at Patreon. If you are going to do anything with it, check for is_email_verified value in the return, and only use this as account email etc if it is shown as verified.

However, when trying to integrate it and check over when people do a login with Patreon, it often says their email is not verified when it should be.

In a case I had today, a user has had the same email on their Patreon account for years. Does the Patreon website not tell people in a really prominent way if their account email is not verified and allow them to easily verify it? Or is this an API problem with not getting it correct?

**Comment by codebard** [comment]
If the result from a call for a user is coming as his/her email not being verified at Patreon, then you should treat it as non-verified. The age of an account is not a factor in this. Since Patreon didnt use to force verification of emails there should be ample amount of old accounts not yet verified.

However if you are querying an account whose email you **_know_** for sure to be verified (ie your patron test account), then this would constitute some situation to investigate...

**Comment by LiamDawe** [comment]
Okay but that doesn't answer my other bit, how do Patron's know their email isn't verified? If you didn't used to require verification, should this not be announced to everyone not verified and start getting it properly cleaned up?

**Comment by codebard** [comment]
That's not within the scope of api or the library. From my usage of Patreon, i dont see any notification or setting that tells me my email is verified or not verified. This verification and any notifications which pertain to email verification are not in the scope of the api, this library, or platform team. Its in a different domain and you could open a support ticket at Patreon zendesk to ask about it.
